### ISSUE TITLE
EAS build ignores androidNavigationBar in 45.0.4

### ISSUE THREAD

**Issue by injecteer** [expo/eas-build#112]
Using  "expo": "~45.0.4" and the following app.json:

```
{
  "expo": {
    "androidNavigationBar": {
      "backgroundColor":"#363636"
    }
  }
}
```
The `expo build:android -t apk` results in correct colouring of the Android NavBar whereas the `eas build --profile preview --platform android` leaves the NavBar in default colors.

The pictures can be seen [here](https://stackoverflow.com/questions/72393840/expo-eas-build-ignores-background-color)

See also https://github.com/expo/expo/issues/13062

**Comment by wkozyra95** [comment]
Closng in favor of the issue in expo/expo. It does not seem to be an issue related to EAS.

**Comment by injecteer** [comment]
Well the issue IS related to EAS, as in dev mode and older expo-build it's not present!
