### ISSUE TITLE
Getting error bash: ./gradlew: Permission denied

### ISSUE THREAD

**Issue by code4muktesh** [expo/eas-build#132]
When building with EAS `eas build --platform android `geting error as:

```
Running './gradlew :app:bundleRelease' in /home/expo/workingdir/build/AppName/android

[stderr] bash: ./gradlew: Permission denied

Error: Gradle build failed with unknown error. Please see logs for the "Run gradlew" phase.
```

**Comment by manarbenkraouda** [comment]
I have the exact same issue since today.

I've made a successful build last week and retried it with the same commit today to check if it wasn't my code or the configuration (which I havn't changed since two months) with no success.

**Comment by wkozyra95** [comment]
Fixed in https://github.com/expo/eas-build/commit/9a669be62c53e26b3ae972d47d0d1d012232bb4b
