### ISSUE TITLE
Building failed

### ISSUE THREAD

**Issue by sylvey** [expo/eas-build#162]
When building with EAS `eas build --profile development --platform android` geting error as:
```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings
Execution optimizations have been disabled for 1 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.
523 actionable tasks: 523 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```
I'm not sure what causes this error.

**Comment by wkozyra95** [comment]
I recommend posting issues in the `eas-cli` repo, the issue tracker there is more regularly monitored.

It's hard to tell what is the issue, probably the real error was earlier in the logs.

**Comment by sylvey** [comment]
ok, thank you ~

> I recommend posting issues in the `eas-cli` repo, the issue tracker there is more regularly monitored.
> 
> It's hard to tell what is the issue, probably the real error was earlier in the logs.
