### ISSUE TITLE
React Native Firebase Crashlytics - Failing to build on EAS, working when building locally [iOS only]

### ISSUE THREAD

**Issue by hirvesh** [expo/eas-build#173]
Hello 👋

I am trying to get a build of my app which uses React Native Firebase to work. This build includes Crashlytics included (https://rnfirebase.io/crashlytics/usage). The whole setup is supposed to work out of the box using the provided config plugin.

When building on EAS for Android, it builds successfully but for iOS EAS Build fails, but works on my machine. The error is shown below. Build Number on EAS: 18c02dac

The error is as shown below. Any idea what might be causing this?

```
Compiling @react-native-firebase/crashlytics Pods/GoogleDataTransport » GDTCCTNanopbHelpers.m

⚠️  (/Users/expo/Library/Developer/Xcode/DerivedData/OutLater-dwbjyavbaiimauajklmhtukorotn/Build/Intermediates.noindex/ArchiveIntermediates/OutLater/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/GoogleDataTransport.build/Objects-normal/arm64/GDTCCTNanopbHelpers.dia:1:1)

d diagnostics file: error("Failed to open diagnostics file") (in target 'GoogleDataTransport' from project 'Pods')
^ Could not read serialize
▸ ** ARCHIVE FAILED **
```

**Comment by wkozyra95** [comment]
> Build Number on EAS: 18c02dac

This is not a build number, it would need to be a valid UUID.

>  but works on my machine

what do you mean by that? Are you building from xcode or eas build --local?

I don't see any reason to believe this is eas specific issue, it looks to me more like some configuration file is malformed and it fails when parsing. I suspect it's either issue with the project configuration or a problem with a package itself.

I'm closing this issue, If you have reason to believe this is an EAS issue please open a new one in expo/eas-cli repo.
