### ISSUE TITLE
How to append the command options to `npm install` on eas-build service?

### ISSUE THREAD

**Issue by cw1997** [expo/eas-build#175]
As you can see in the screenshot below, because some npm packages are not updated their peer-dependencies version, I need to use `npm install --force` to install the npm dependencies locally. But on the eas-build online service, I don't find a way to add the command options `--force` to `npm install` on eas-build service.
Could I do anything to fix the problem? Or is there any other method to resolve this problem?
In the other way, I expect that eas-build service supports using `npm ci` instead of `npm install` because it will keep consistent dependencies version with package-lock.json, it is the normal behavior.
Thank you very much!

![image](https://user-images.githubusercontent.com/11588555/204261796-1d71c832-9b9b-4224-9ee4-b70e76cadafa.png)

**Comment by wkozyra95** [comment]
You can add npmrc with https://docs.npmjs.com/cli/v7/using-npm/config#legacy-peer-deps
