### ISSUE TITLE
[bug]: `Unable to find a specification for 'UMCore' depended upon by 'EXClipboard¨`

### ISSUE THREAD

**Issue by filiptronicek** [expo/eas-build#58]
I have a managed Expo workflow running on Expo SDK 43.0.3. When I try to build it with EAS build, I get the following:

```
[!] Unable to find a specification for `UMCore` depended upon by `EXClipboard`
```

<details>
<summary>The whole log</summary>

```
Installing pods
Using Expo modules
Auto-linking React Native modules for target `Interclip`: RNCClipboard, RNCMaskedView, RNGestureHandler, RNReanimated, RNSVG, RNScreens, react-native-appearance, react-native-camera, react-native-netinfo, and react-native-safe-area-context
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Adding spec repo `trunk` with CDN `https://cdn.cocoapods.org/`
CocoaPods 1.11.2 is available.
To update use: `sudo gem install cocoapods`
For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.11.2
[!] Unable to find a specification for `UMCore` depended upon by `EXClipboard`
You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
[stderr] [!] `<PBXResourcesBuildPhase UUID=`13B07F8E1A680F5B00A75B9A`>` attempted to initialize an object with an unknown UUID. `E8F051043AFF44E385A2EC31` for attribute: `files`. This can be the result of a merge and the unknown UUID is being discarded.
pod exited with non-zero code: 1
````

</details>

**Comment by wkozyra95** [comment]
you are most likely using incompatible version of `expo-clipoard`, use expo install to ensure the correct version is installed

Closing issue, if problem persist please open issue in expo/expo repo unless you have reason to believe that problem is eas specific

**Comment by ArthurDias01** [comment]
Im currently having the same issue but with EXPermission:

⚠️  Something went wrong running `pod install` in the `ios` directory.
Command `pod repo update` failed.
└─ Cause: Couldn't install: EXPermissions » UMCore. Ensure the CocoaPod "UMCore" is installed in your project, then run `npx pod-install` to try again.

have tried the solution above without success....

**Comment by pihomeserver** [comment]
Same issue than @ArthurDias01 with `eas build`. No issue with `expo build`

**Comment by pihomeserver** [comment]
@ArthurDias01 found a solution : 
- Go to your root app folder and run `expo install expo-permissions`
- go to ios subfolder and run `pod install --repo-update --clean-install`
In my case it solved the issue and i was able to build my with eas
