### ISSUE TITLE
npm v7+ monorepos are broken in EAS

### ISSUE THREAD

**Issue by byCedric** [expo/eas-build#90]
I know we don't "officially support" npm workspaces, but would be great if it worked. One of the big issues with npm v7+ for React Native is the peer dependencies. We often encounter these peer deps issues in React Native, but we have no way of turning this off in EAS build.

## Issue

What's going on is that monorepos with npm v7 needs to be installed (`npm install`) from the root of the monorepo. When running `npm install` inside the **apps/my-app**, it fails because it can't find the right monorepo packages.

A weird behavior I found is, you can actually turn this off [with the .npmrc file](https://docs.npmjs.com/cli/v8/using-npm/config#workspaces). But adding this to the root of the monorepo, or globally in the worker, still doesnt get picked up when running `npm install` inside the **apps/my-app** folder.

## Proposed fix

Instead of calling `<packageManager> install` on [this line](https://github.com/expo/eas-build/blob/3383c40fad8454a4ab4017f8c6997bf3e9d99432/packages/build-tools/src/utils/prebuild.ts#L24), we might want to rely on package manager to resolve to the right monorepo root instead. That, combined with the "find workspace root" method [I RFC'd in this PR](https://github.com/expo/expo-cli/pull/4311) should get us support for all package managers in `@expo/package-manager`.

One thing I don't necessarily like is that we force people to use one of the package manager supported managers. If we have a `installCommand` in EAS json, we could let the user decide however they want to install the node modules inside the project. But that's just a pet peeve 🤷 

## Example of failures

- npm v7 - https://expo.dev/accounts/bycedric/projects/eas-benchmark-npm-v7
- npm v8 - https://expo.dev/accounts/bycedric/projects/eas-benchmark-npm-v8

**Comment by wkozyra95** [comment]
Hi, I missed that issue
For future reference probably best to report/propose stuff like that on slack or linear and ping me and Dominik there

> Instead of calling <packageManager> install on [this line](https://github.com/expo/eas-build/blob/3383c40fad8454a4ab4017f8c6997bf3e9d99432/packages/build-tools/src/utils/prebuild.ts#L24), we might want to rely on package manager to resolve to the right monorepo root instead.

It looks like we are already doing it for the initial install here https://github.com/expo/eas-build/blob/f1abc21a3da8049a241edfc902e378ac8523f081/packages/build-tools/src/utils/project.ts#L98 but not for the second install after prebuild.

added issue on linear https://linear.app/expo/issue/ENG-4873/support-npm-workspaces

> One thing I don't necessarily like is that we force people to use one of the package manager supported managers.

I would like to avoid adding new custom commands in eas.json and just handle all "reasonable" package managers.
